### ISSUE TITLE
SQLAlchemy 2.0 support

### ISSUE THREAD

**Issue by gergelypolonkai** [ri-gilfanov/aiohttp-sqlalchemy#11]
Will this library support SQLAlchemy 2.0? The docs say it’s SQLA 1.4/2.0 for aiohttp, but the dependencies are stuck with 1.4.

**Comment by ri-gilfanov** [comment]
@gergelypolonkai , try release 1.0.0.

Support for SQLA 1.4 has been dropped.

Support for SQLA 2.0 has been added.
